FROM centos:7

WORKDIR /etc/splunk-appinspect


RUN yum install -y python3 python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install splunk-appinspect  

ENV LC_ALL=en_US.utf-8
ENV LANG=en_US.utf-8

#Validate splunk-appinspect is installed
RUN splunk-appinspect list version


COPY Scripts/validate.sh validate.sh
COPY AppList/ AppList/
COPY Rules/*.py Rules/

RUN chmod +x validate.sh

ENTRYPOINT ["/etc/splunk-appinspect/validate.sh"]